name: .NET Publish to GitHub

on:
  workflow_dispatch:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push "**/*.nupkg" -k ${GITHUB_TOKEN} -s "https://nuget.pkg.github.com/adv-appmod/index.json" --skip-duplicate  
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
